### ISSUE TITLE
bro I can't install it..plz provide us a docs to help us install it

### ISSUE THREAD

**Issue by ysdragon** [fatkulnurk/filehosting-video-stream#1]
bro I can't install it..plz provide us a docs to help us install it

**Comment by SStrTrop** [comment]
I cant install it too, i dont know why we need lanaver something to install a script

**Comment by mrnitr0** [comment]
Yes, he should provide us a sql database.

**Comment by fatkulnurk** [comment]
please wait, I will provide the documentation as soon as possible. thanks.

**Comment by therealbala** [comment]
> bro I can't install it..plz provide us a docs to help us install it

1. enter db details on. env.example
2. change .env.example to .env
3. migrate db php artisan migrate
4. seed db php artisan migrate --seed
5. done 😃

![InShot_20201126_134055093](https://user-images.githubusercontent.com/75065725/100324560-6e58cc80-2fed-11eb-9982-b6498373c30a.jpg)

**Comment by kaizoku75** [comment]
where is the documentation?
